language: cpp

os:
    - windows

git:
  submodules: true

env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2015\BuildTools\MSBuild\14.0\Bin"

install:
  - choco install -y vcbuildtools --version 2015.4 --force

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - cmd.exe /C 'MSBuild.exe Aegisub.sln /p:Configuration=Release /p:Platform=x64'
