language: cpp

os:
  - windows

git:
  submodules: false

install:
  - choco install -y vcbuildtools --version 2015.4 --force

script:
  - export PATH="C:\\Program Files (x86)\\MSBuild\\14.0\\Bin":$PATH
  - export VCTargetsPath="C:\\Program Files (x86)\\MSBuild\\Microsoft.cpp\\v4.0\\v140"
  - cmd.exe /C 'dotnet.exe msbuild Aegisub.sln /p:Configuration=Release /p:Platform=x64'
