language: cpp

os:
  - windows

git:
  submodules: false

env:
  - MSBUILD_PATH="C:\Program Files (x86)\MSBuild\14.0\Bin"

install:
  - choco install -y vcbuildtools --version 2015.4 --force

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - cmd.exe /C 'dir C:\Users\travis\AppData\Local'
  - cmd.exe /C 'dir C:\Users\travis\AppData\Local\Microsoft'
  - cmd.exe /C 'dir C:\Users\travis\AppData\Local\Microsoft\MSBuild'
  - cmd.exe /C 'dir C:\Users\travis\AppData\Local\Microsoft\MSBuild\v4.0'
  - cmd.exe /C 'MSBuild.exe Aegisub.sln /p:Configuration=Release /p:Platform=x64'
