image: Visual Studio 2017

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - MSBuild.exe Aegisub.sln /m

platform: x64
configuration: Release

