image: Visual Studio 2017

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - MSBuild.exe "%APPBEYOR_BUILD_FOLDER\Aegisub.sln" /m

platform: x64
configuration: Release

