image: Visual Studio 2017

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=C:\yasm;%PATH%
  - mkdir C:\yasm
  - curl -o "C:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - MSBuild.exe Aegisub.sln /target:BuildTasks
  - MSBuild.exe Aegisub.sln /m /p:Configuration=Release /p:Platform=x64

artifacts:
  - path: bin
