image: Visual Studio 2017

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=C:\yasm;%PATH%
  - mkdir C:\yasm
  - curl -o "C:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - MSBuild.exe Aegisub.sln /target:BuildTasks
  - MSBuild.exe Aegisub.sln /m /p:Configuration=Release /p:Platform=x64

after_build:
  - curl -o "C:\aegisub-codecs.zip" http://mugen.karaokes.moe/downloads/aegisub-codecs.zip
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z x "C:\aegisub-codecs.zip"
  - cd packages\win_installer
  - iscc aegisub3.iss

artifacts:
  - path: packages\win_installer\output\Aegisub-Japan7-x64.exe
