image: Visual Studio 2017

build_script:
  - MSBuild.exe "C:\projects\aegisub\Aegisub.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

platform: x64
configuration: Release

