image: Visual Studio 2015

install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build:
  parallel: true
  project: Aegisub.sln

platform: x64
configuration: Release

